# @package _global_

llm:
  _target_: gigaevo.llm.models.create_multi_model_router
  model_configs:
    - model: ${constants.default_model_name}
      temperature: ${constants.default_temperature}
      max_tokens: ${constants.default_max_tokens}
      top_p: ${constants.default_top_p}
      top_k: ${constants.default_top_k}
      base_url: ${constants.default_llm_base_url}
      request_timeout: ${constants.default_request_timeout}
  probabilities: [1.0]
  api_key: ${oc.env:OPENAI_API_KEY}
