# @package _global_

llm:
  _target_: gigaevo.llm.models.MultiModelRouter
  _convert_: all
  models:
    - _target_: langchain_openai.ChatOpenAI
      model: ${model_name}
      api_key: ${oc.env:OPENAI_API_KEY}
      temperature: ${temperature}
      max_tokens: ${max_tokens}
  probabilities: [1.0]
