# @package _global_

logging:
  level: DEBUG
  log_dir: ${constants.log_dir}
  rotation: ${constants.log_rotation}
  retention: ${constants.log_retention}

tb_config:
  _target_: gigaevo.utils.tb_logger.TBConfig
  logdir: ${constants.log_dir}/tb_logs

writer:
  _target_: gigaevo.utils.tb_logger.init_tb
  cfg: ${tb_config}
