# @package _global_

runner_config:
  _target_: gigaevo.runner.dag_runner.DagRunnerConfig
  poll_interval: ${constants.runner_poll_interval}
  max_concurrent_dags: ${constants.max_concurrent_dags}
  dag_timeout: ${constants.dag_timeout}

dag_runner:
  _target_: gigaevo.runner.dag_runner.DagRunner
  storage: ${ref:redis_storage}
  dag_blueprint: ${dag_blueprint}
  config: ${runner_config}
  writer: ${writer}

evolution_runner:
  _target_: gigaevo.runner.runner.EvolutionRunner
  dag_runner: ${dag_runner}
  evolution_engine: ${evolution_engine}
