# @package _global_

# Manual definition of the pipeline via stages and edges

evolution_context:
  _target_: gigaevo.entrypoint.evolution_context.EvolutionContext
  problem_ctx: ${problem_context}
  llm_wrapper: ${llm}
  storage: ${redis_storage}

dag_blueprint:
  _target_: src.runner.dag_blueprint.DAGBlueprint
  nodes:
    ValidateCodeStage:
      _target_: src.programs.stages.validation.ValidateCodeStage
      _partial_: true
      max_code_length: ${constants.max_code_length}
      timeout: ${constants.stage_timeout}
      safe_mode: true

  data_flow_edges: []

  max_parallel_stages: ${constants.dag_concurrency}
  dag_timeout: ${constants.dag_timeout}
