# @package _global_

evolution_context:
  _target_: src.entrypoint.evolution_context.EvolutionContext
  problem_ctx: ${problem_context}
  llm_wrapper: ${llm}
  storage: ${redis_storage}

pipeline_builder:
  _target_: src.entrypoint.default_pipelines.DefaultPipelineBuilder
  ctx: ${evolution_context}

dag_blueprint:
  _target_: src.config.helpers.build_dag_from_builder
  builder: ${pipeline_builder}
