# @package _global_

program_loader:
  _target_: gigaevo.problems.initial_loaders.RedisTopProgramsLoader
  source_host: ${redis.host}
  source_port: ${redis.port}
  source_db: ${loader.source_db}
  key_prefix: ${problem.name}_evolution
  metric_key: ${primary_key}
  higher_is_better: ${higher_is_better}
  top_n: ${loader.top_n}

loader:
  source_db: 0
  top_n: 50
